stages:
  - build
  - test
  - deploy

variables:
  SSH_HOST: "vango@83.233.229.193"
  PROJECT_PATH: "/home/vango/projects/SwarmSync"
  DOCKER_COMPOSE_FILE: "docker-compose.yml"

before_script:
  # Start the SSH agent
  - eval $(ssh-agent -s)
  # Add the private SSH key to the agent
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
  # Ensure the .ssh directory is created and properly secured
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  # Add the public key to known_hosts (for the server's identity check)
  - ssh-keyscan -H "$SSH_HOST" >> ~/.ssh/known_hosts
  - chmod 600 ~/.ssh/known_hosts

build:
  stage: build
  script:
    - echo "Triggering build on Ubuntu server..."
    - ssh "$SSH_HOST" <<EOF
      cd $PROJECT_PATH
      git pull origin master
      docker-compose -f $DOCKER_COMPOSE_FILE build
      EOF
  only:
    - master

integration_tests:
  stage: test
  script:
    - echo "Running integration tests on Ubuntu server..."
    - ssh "$SSH_HOST" <<EOF
      cd $PROJECT_PATH
      docker-compose -f $DOCKER_COMPOSE_FILE run --rm integration_test
      EOF
  only:
    - master

deploy:
  stage: deploy
  script:
    - echo "Deploying Core to Ubuntu server..."
    - ssh "$SSH_HOST" <<EOF
      cd $PROJECT_PATH
      docker-compose -f $DOCKER_COMPOSE_FILE up -d core
      EOF
  only:
    - master
  when: on_success
