[package]
name = "proto_definitions"
version = "0.1.0"
edition = "2024"
build = "build.rs"

[dependencies]
tonic = { workspace = true }
prost = { workspace = true }
tonic-build = { workspace = true }

[build-dependencies]
tonic-build = { workspace = true}
