services:
  consumer:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder # use your builder stage so Rust toolchain is present
    volumes:
      - .:/usr/src/consumer # mount your source in
    working_dir: /usr/src/consumer
    entrypoint: ["tail", "-f", "/dev/null"] # keep the container alive

  consumer-test:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    volumes:
      - .:/usr/src/consumer
    working_dir: /usr/src/consumer
    entrypoint: ["cargo"]
    command: ["test"]
