FROM rust:latest

# Install build + runtime dependencies
RUN apt-get update && apt-get install -y \
  cmake \
  build-essential \
  pkg-config \
  libssl-dev \
  netcat-openbsd \
  && rm -rf /var/lib/apt/lists/*


WORKDIR /app

COPY . .

RUN cargo install diesel_cli --no-default-features --features postgres
RUN cargo install cargo-watch

WORKDIR /app/core

CMD ["cargo", "watch", "-x", "run --bin core"]








