FROM rust:latest

# Install build dependencies, including netcat
RUN apt-get update && apt-get install -y \
  cmake \
  build-essential \
  pkg-config \
  libssl-dev \
  netcat-openbsd \
  && rm -rf /var/lib/apt/lists/*

# Set workspace root
WORKDIR /app

# Copy the entire workspace into the container
COPY . .

# Install dev tools like cargo-watch
RUN cargo install cargo-watch

# Switch to admin_shell folder for dev runs
WORKDIR /app/admin_shell

# Default dev command to watch and run
CMD ["cargo", "watch", "-x", "run"]



